version: "3.9"

services:
  custom:
    build:
      context: .
      dockerfile: ./docker/custom.Dockerfile
    container_name: custom
    init: true
    ports:
      - 8092:3000
    stdin_open: true
    tty: true
    command: /bin/bash

  lazynvim:
    build:
      context: .
      dockerfile: ./docker/lazynvim.Dockerfile
    container_name: lazynvim
    init: true
    stdin_open: true
    tty: true
    command: /bin/bash

  lunarvim:
    build:
      context: .
      dockerfile: ./docker/lunarvim.Dockerfile
    container_name: lunarvim 
    init: true
    stdin_open: true
    tty: true
    command: /bin/bash

  wansmer:
    build:
      context: .
      dockerfile: ./docker/wansmer.Dockerfile
    container_name: wanmer 
    init: true
    stdin_open: true
    tty: true
    command: /bin/bash
    
  nvchad:
    build:
      context: .
      dockerfile: ./docker/nvchad.Dockerfile
    container_name: nvchad 
    init: true
    stdin_open: true
    tty: true
    command: /bin/bash
